-- One mass text send.
--
-- request_id is generated by the browser and unique per tenant, so a
-- retried request — a timeout partway through several hundred messages is
-- the likely case — finds the existing batch and resumes it instead of
-- texting everybody a second time. There is no undo on a text.
CREATE TABLE `mass_text_batches` (
  `id` int AUTO_INCREMENT NOT NULL,
  `tenant_id` int NOT NULL,
  `request_id` varchar(64) NOT NULL,
  `body` text NOT NULL,
  `audience` text,
  `status` enum('sending','complete','failed') NOT NULL DEFAULT 'sending',
  `sent_by_user_id` int,
  `created_at` timestamp NOT NULL DEFAULT (now()),
  `completed_at` timestamp NULL,
  CONSTRAINT `mass_text_batches_id` PRIMARY KEY(`id`),
  CONSTRAINT `uq_mass_text_batches_request` UNIQUE(`tenant_id`,`request_id`)
);
