-- The column half of "one PAID payment row per Stripe invoice".
-- The unique index over it is migration 0095, which must follow this one.
--
-- Stripe emits both `invoice.paid` and `invoice.payment_succeeded` for a
-- single successful charge. The webhook checked for an existing row before
-- inserting, but check-then-insert is not atomic: on 08/10/2026 the two
-- events arrived in the same second, both handlers read "nothing booked",
-- and both inserted. One $1 charge, two payment rows and two ledger
-- entries. Revenue silently overstated, intermittently, with nothing wrong
-- on screen. The same pair on 30/09/2026 arrived far enough apart to be
-- caught, which is what makes it easy to miss.
--
-- Why a separate column rather than a unique index on stripe_invoice_id:
-- FAILED rows carry an invoice id too (`invoice.payment_failed` writes
-- one), and Stripe resends that event across its retry schedule, so one
-- invoice legitimately produces several failed rows. Constraining the raw
-- column would reject them. The invariant that is actually true is "at most
-- one PAID row per invoice", and this column holds the invoice id only for
-- the row that booked the money. NULL everywhere else, and MySQL lets NULLs
-- repeat freely in a unique index.
--
-- Why not a GENERATED column, which could not drift: TiDB documents that
-- ALTER TABLE cannot add a STORED generated column to an existing table,
-- while its ADD COLUMN page says otherwise. A migration that may fail
-- part-way against the live salon is not worth the elegance.
--
-- Why this is split from the index: TiDB refuses to index a column added in
-- the same ALTER — "column does not exist: paid_invoice_key". It validates
-- the whole statement first, so that attempt applied nothing, but two
-- statements in one migration could have left the column added and the
-- migration unrecorded. One statement per migration means a failure is
-- always recorded truthfully.
ALTER TABLE `membership_payments` ADD COLUMN `paid_invoice_key` VARCHAR(255) NULL;
