import { useState } from "react";
import { CalendarDays, CheckCircle2, Clock3, PawPrint, ShieldCheck, UserRound } from "lucide-react";
import { trpc } from "@/lib/trpc";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import { toast } from "sonner";
import {
  getEligibleOnlineBookingServices,
  getPetWeightBand,
  getWeightEligibilityMessage,
} from "@shared/onlineBookingWeightEligibility";
import {
  ONLINE_BOOKING_DATE_FIELD_LAYOUT,
  ONLINE_BOOKING_TOP_ROW_GRID,
} from "@/lib/onlineBookingFormLayout";
import { getBookingGroomerDisplayName } from "../../../shared/bookingGroomerDisplay";

export default function OnlineBooking({ previewMode = false }: { previewMode?: boolean }) {
  const publicProfiles = trpc.onlineBooking.listGroomerProfiles.useQuery({ tenantId: 1 }, { enabled: !previewMode });
  const previewProfiles = trpc.onlineBooking.listPreviewGroomerProfiles.useQuery({ tenantId: 1 }, { enabled: previewMode });
  const groomers = previewMode ? previewProfiles.data : publicProfiles.data;
  const isLoading = previewMode ? previewProfiles.isLoading : publicProfiles.isLoading;
  const [form, setForm] = useState({ firstName: "", lastName: "", phone: "", email: "", petName: "", breed: "", weightKg: "", staffId: "", serviceType: "classic_groom", scheduledStart: "", notes: "" });
  const [selectedDate, setSelectedDate] = useState("");
  const [complete, setComplete] = useState(false);
  const create = trpc.onlineBooking.createGuest.useMutation({
    onSuccess: () => { setComplete(true); toast.success("Booking request received"); },
    onError: error => toast.error(error.message),
  });
  const createPreview = trpc.onlineBooking.createPreviewGuest.useMutation({
    onSuccess: () => { setComplete(true); toast.success("Preview test booking created"); },
    onError: error => toast.error(error.message),
  });
  const selectedWeightBand = getPetWeightBand(form.weightKg);
  const serviceOptions = getEligibleOnlineBookingServices(form.weightKg);
  const canLoadSlots = Boolean(form.staffId && selectedWeightBand && selectedDate);
  const slotInput = { tenantId: 1, staffId: Number(form.staffId), serviceType: form.serviceType as any, petWeightKg: Number(form.weightKg), date: selectedDate };
  const publicSlots = trpc.onlineBooking.listAvailableSlots.useQuery(slotInput, { enabled: !previewMode && canLoadSlots });
  const previewSlots = trpc.onlineBooking.listPreviewAvailableSlots.useQuery(slotInput, { enabled: previewMode && canLoadSlots });
  const availableSlots = previewMode ? previewSlots.data : publicSlots.data;
  const slotsLoading = previewMode ? previewSlots.isLoading : publicSlots.isLoading;
  const creating = previewMode ? createPreview.isPending : create.isPending;
  const submitRequest = () => {
    const input = { tenantId: 1, firstName: form.firstName, lastName: form.lastName, phone: form.phone, email: form.email, petName: form.petName, breed: form.breed || undefined, weightKg: Number(form.weightKg), staffId: Number(form.staffId), serviceType: form.serviceType as any, scheduledStart: new Date(form.scheduledStart), notes: form.notes || undefined };
    if (previewMode) createPreview.mutate(input); else create.mutate(input);
  };
  if (complete) return <main className="min-h-screen bg-gradient-to-br from-teal-950 via-slate-950 to-cyan-950 flex items-center justify-center px-5 py-12 text-white"><div className="max-w-md text-center rounded-3xl border border-teal-300/30 bg-white/10 backdrop-blur p-8 shadow-2xl"><div className="mx-auto w-fit rounded-2xl bg-emerald-400/20 p-4"><CheckCircle2 className="h-10 w-10 text-emerald-300" /></div><h1 className="mt-5 text-2xl font-bold">{previewMode ? "Preview booking recorded" : "Booking request received"}</h1><p className="mt-3 text-teal-100">{previewMode ? "This is a marked preview test. No client message, automatic confirmation or live booking release has occurred." : "Thank you. We have reserved your requested time pending confirmation from Barkin’ Beautiful."}</p><Button className="mt-6 bg-teal-400 text-slate-950 hover:bg-teal-300" onClick={() => { setComplete(false); setSelectedDate(""); setForm({ firstName: "", lastName: "", phone: "", email: "", petName: "", breed: "", weightKg: "", staffId: "", serviceType: "classic_groom", scheduledStart: "", notes: "" }); }}>Book another visit</Button></div></main>;

  return <main className="min-h-screen bg-[radial-gradient(circle_at_top_left,_#115e5988,_transparent_40%),linear-gradient(135deg,#041f24,#0f172a_55%,#052e2b)] px-4 py-8 text-slate-900 sm:px-6"><div className="mx-auto max-w-5xl"><header className="mb-8 flex flex-col gap-4 text-white sm:flex-row sm:items-center sm:justify-between"><div className="flex items-center gap-3"><img src="/barkin_beautiful_logo.png" alt="Barkin’ Beautiful" className="h-14 w-14 rounded-xl object-contain bg-white p-1" /><div><p className="text-xs font-semibold uppercase tracking-[0.2em] text-teal-300">Barkin’ Beautiful</p><h1 className="text-2xl font-bold">Book your groom</h1></div></div><div className="flex items-center gap-2 text-sm text-teal-100"><PawPrint className="h-4 w-4 text-teal-300" /> Powered by Groomigo</div></header>
    <div className="grid gap-6 lg:grid-cols-[1fr_320px]"><section className="rounded-3xl bg-white p-5 shadow-2xl sm:p-8">{previewMode && <div className="mb-5 rounded-xl border border-amber-300 bg-amber-50 px-4 py-3 text-sm text-amber-900"><strong>Preview mode only.</strong> Every request is marked as a test. No client messages, automatic confirmations or live booking release will occur.</div>}<div className="mb-6"><h2 className="text-xl font-bold">Choose a preferred groomer</h2><p className="mt-1 text-sm text-slate-500">Availability is protected by live capacity limits. A booking request is confirmed only after the salon accepts it.</p></div>
      {isLoading ? <p className="py-12 text-center text-slate-500">Loading groomer profiles…</p> : !groomers?.length ? <div className="rounded-xl border border-dashed p-8 text-center"><ShieldCheck className="mx-auto h-8 w-8 text-teal-600" /><h3 className="mt-3 font-semibold">Online booking is coming soon</h3><p className="mt-1 text-sm text-slate-500">The salon has not released any groomer profiles for online bookings yet.</p></div> : <>
        <div className="grid gap-3 sm:grid-cols-2" aria-label="Available groomers">{groomers.map(groomer => <button type="button" key={groomer.id} onClick={() => { setForm(p => ({ ...p, staffId: String(groomer.id), scheduledStart: "" })); }} className={`rounded-2xl border p-4 text-left transition ${form.staffId === String(groomer.id) ? "border-teal-600 bg-teal-50 ring-2 ring-teal-200" : "hover:border-teal-300 hover:bg-teal-50/50"}`}><div className="flex items-center gap-3"><div className="grid h-10 w-10 place-items-center overflow-hidden rounded-full font-bold text-white" style={{ background: groomer.colourHex }}>{groomer.photoUrl ? <img src={groomer.photoUrl} alt="" className="h-full w-full object-cover" /> : groomer.name[0]}</div><div><p className="font-semibold">{getBookingGroomerDisplayName(groomer.name)}</p><p className="text-xs capitalize text-slate-500">{groomer.role}</p></div></div>{groomer.bio && <p className="mt-3 line-clamp-2 text-sm text-slate-600">{groomer.bio}</p>}</button>)}</div>
        <div className={`mt-7 ${ONLINE_BOOKING_TOP_ROW_GRID}`}><div className="min-w-0"><Label>Dog’s weight (kg)</Label><Input className="mt-1.5" type="number" min="0" max="80" step="0.1" value={form.weightKg} onChange={e => { setForm(p => ({ ...p, weightKg: e.target.value, scheduledStart: "" })); }} placeholder="e.g. 14.5" /></div><div className="min-w-0"><Label>Service</Label><Select disabled={!selectedWeightBand} value={form.serviceType} onValueChange={value => { setForm(p => ({ ...p, serviceType: value, scheduledStart: "" })); }}><SelectTrigger className="mt-1.5 w-full"><SelectValue placeholder="Enter weight first" /></SelectTrigger><SelectContent>{serviceOptions.map(({ value, label }) => <SelectItem key={value} value={value}>{label}</SelectItem>)}</SelectContent></Select></div><div className={ONLINE_BOOKING_DATE_FIELD_LAYOUT}><Label>Choose a date</Label><Input className="mt-1.5 w-full" type="date" min={new Date().toISOString().slice(0, 10)} value={selectedDate} onChange={e => { setSelectedDate(e.target.value); setForm(p => ({ ...p, scheduledStart: "" })); }} /></div></div>
        <p className={`mt-2 text-sm ${selectedWeightBand ? "text-teal-700" : "text-amber-700"}`}>{getWeightEligibilityMessage(form.weightKg)}</p>
        <div className="mt-5 rounded-2xl border border-teal-100 bg-teal-50/50 p-4"><div className="flex items-center gap-2"><Clock3 className="h-4 w-4 text-teal-700" /><h3 className="font-semibold text-slate-900">Available times</h3></div>{!canLoadSlots ? <p className="mt-2 text-sm text-slate-600">Choose a groomer, valid dog weight and date to see available times.</p> : slotsLoading ? <p className="mt-2 text-sm text-slate-600">Finding available times…</p> : !availableSlots?.length ? <p className="mt-2 text-sm text-amber-800">No times are available for this date. Please choose another day or groomer.</p> : <div className="mt-3 flex flex-wrap gap-2">{availableSlots.map(slot => { const isSelected = form.scheduledStart === new Date(slot.scheduledStart).toISOString(); return <Button key={new Date(slot.scheduledStart).toISOString()} type="button" variant={isSelected ? "default" : "outline"} className={isSelected ? "bg-teal-700 hover:bg-teal-800" : "bg-white hover:bg-teal-50"} onClick={() => setForm(p => ({ ...p, scheduledStart: new Date(slot.scheduledStart).toISOString() }))}>{new Date(slot.scheduledStart).toLocaleTimeString("en-AU", { timeZone: "Australia/Brisbane", hour: "numeric", minute: "2-digit" })}</Button>; })}</div>}{form.scheduledStart && <p className="mt-3 text-sm font-medium text-emerald-700">Selected time: {new Date(form.scheduledStart).toLocaleString("en-AU", { timeZone: "Australia/Brisbane", weekday: "short", day: "numeric", month: "short", hour: "numeric", minute: "2-digit" })}</p>}</div>
        <div className="mt-8 border-t pt-6"><h2 className="text-xl font-bold">Your details</h2><div className="mt-4 grid gap-4 sm:grid-cols-2"><div><Label>First name</Label><Input className="mt-1.5" value={form.firstName} onChange={e => setForm(p => ({ ...p, firstName: e.target.value }))} /></div><div><Label>Last name</Label><Input className="mt-1.5" value={form.lastName} onChange={e => setForm(p => ({ ...p, lastName: e.target.value }))} /></div><div><Label>Mobile number</Label><Input className="mt-1.5" value={form.phone} onChange={e => setForm(p => ({ ...p, phone: e.target.value }))} placeholder="04xx xxx xxx" /></div><div><Label>Email <span className="text-slate-400">(optional)</span></Label><Input className="mt-1.5" type="email" value={form.email} onChange={e => setForm(p => ({ ...p, email: e.target.value }))} /></div><div><Label>Pet’s name</Label><Input className="mt-1.5" value={form.petName} onChange={e => setForm(p => ({ ...p, petName: e.target.value }))} /></div><div><Label>Breed <span className="text-slate-400">(optional)</span></Label><Input className="mt-1.5" value={form.breed} onChange={e => setForm(p => ({ ...p, breed: e.target.value }))} /></div><div className="sm:col-span-2"><Label>Anything we should know?</Label><Textarea className="mt-1.5" value={form.notes} onChange={e => setForm(p => ({ ...p, notes: e.target.value }))} placeholder="Coat condition, behaviour, style preference or special requirements." /></div></div></div>
        <Button className="mt-6 w-full bg-teal-700 hover:bg-teal-800" disabled={!form.scheduledStart || !selectedWeightBand || creating || !form.firstName || !form.lastName || !form.phone || !form.petName} onClick={submitRequest}>{creating ? "Submitting request…" : previewMode ? "Create preview booking" : "Request this booking"}</Button>
      </>}</section>
      <aside className="h-fit rounded-3xl border border-white/15 bg-white/10 p-5 text-white backdrop-blur"><Clock3 className="h-6 w-6 text-teal-300" /><h2 className="mt-3 font-bold">A calmer way to book</h2><p className="mt-2 text-sm leading-6 text-teal-50">Choose a groomer you know and love, or select first available when the salon opens that option. Slot capacity is checked live so the day never becomes overbooked.</p><div className="mt-5 space-y-3 border-t border-white/15 pt-5 text-sm text-teal-50"><div className="flex gap-2"><UserRound className="h-4 w-4 flex-none text-teal-300" />Each pet is assessed separately, even in multi-pet families.</div><div className="flex gap-2"><CalendarDays className="h-4 w-4 flex-none text-teal-300" />Bath-only services have a protected daily online limit.</div></div></aside>
    </div></div></main>;
}
